### ISSUE TITLE
I can't see all the options

### ISSUE THREAD

**Issue by alejandro-rios** [EarlOfEgo/Jetpack-Compose-preview-creator#6]
Hello, first of all, awesome job building this plugin, I installed it but in the settings I don't see all the options you show in the JetBrains page.

![image](https://github.com/user-attachments/assets/90e96998-619a-4a87-9bbb-cdeff98893de)

I'm on Android Studio LadyBug patch 3.

**Comment by EarlOfEgo** [comment]
Hey, thanks for using the plugin and your feedback. 
I added the settings just recently and they will be there with the next version 1.1.0. I added the screenshot before waiting till the marketplace review is done.
If you can't wait, you can download also this version here: https://github.com/EarlOfEgo/Jetpack-Compose-preview-creator/releases/tag/v1.1.0
